### ISSUE TITLE
Double-check Hydra Version

### ISSUE THREAD

**Issue by chao1224** [jiaor17/DiffCSP#4]
Hi authors,

Thank you for providing the code base.

I am wondering what hydra version you are using. I am getting the following exception:
```
  File "xxx/anaconda3/envs/Crystallization/lib/python3.7/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
AttributeError: module 'diffcsp' has no attribute 'pl_data'
```

I tried hydra-core==1.3.2 and 1.2.0. Neither can work.

**Comment by jiaor17** [comment]
Hi,

We use `hydra-core==1.1.0` as the hydra version.
